import jsImg from "./assets/courses/js.png";
import cssImg from "./assets/courses/css.png";
import nodeImg from "./assets/courses/node.png";
import vueImg from "./assets/courses/vue.png";
import pythonImg from "./assets/courses/python.png";
import mlImg from "./assets/courses/ml.png";
import mernImg from "./assets/courses/mern.png";
import flutterImg from "./assets/courses/flutter.png";
import blockchainImg from "./assets/courses/blockchain.png";
import designImg from "./assets/courses/designing.png";
import tableauImg from "./assets/courses/tableau.png";
import cybersecurityImg from "./assets/courses/cybersecurity.png";
import unityImg from "./assets/courses/unity.png";
import cloudImg from "./assets/courses/cloud.png";

import sample1 from "./assets/courses/sample1.mp4";
import sample2 from "./assets/courses/sample2.mp4";
import sample3 from "./assets/courses/sample3.mp4";

import { FaRegPlayCircle } from "react-icons/fa";

const coursesOld = [
	{
		id: 1,
		name: "Advanced JavaScript Concepts",
		skills: "JavaScript, ES6, Asynchronous Programming",
		rating: 4.7,
		reviews: "5K",
		level: "Intermediate",
		type: "Guided Project",
		duration: "10 hours",
		img: jsImg,
	},
	{
		id: 2,
		name: "Responsive Web Design with CSS",
		skills: "CSS, Flexbox, Grid, HTML",
		rating: 4.6,
		reviews: "8K",
		level: "Beginner",
		type: "Guided Project",
		duration: "6 hours",
		img: cssImg,
	},
	{
		id: 3,
		name: "Building RESTful APIs with Nodejs",
		skills: "Node.js, Express, MongoDB",
		rating: 4.8,
		reviews: "3K",
		level: "Intermediate",
		type: "Guided Project",
		duration: "12 hours",
		img: nodeImg,
	},
	{
		id: 4,
		name: "Introduction to Vuejs",
		skills: "Vue.js, JavaScript, HTML",
		rating: 4.5,
		reviews: "7K",
		level: "Beginner",
		type: "Guided Project",
		duration: "8 hours",
		img: vueImg,
	},
	{
		id: 5,
		name: "Python for Data Science",
		skills: "Python, Pandas, NumPy",
		rating: 4.9,
		reviews: "15K",
		level: "Beginner",
		type: "Guided Project",
		duration: "14 hours",
		img: pythonImg,
	},
	{
		id: 6,
		name: "Introduction to ML",
		skills: "Python, Scikit-Learn, Data Visualization",
		rating: 4.7,
		reviews: "9K",
		level: "Intermediate",
		type: "Guided Project",
		duration: "20 hours",
		img: mlImg,
	},
	{
		id: 7,
		name: "Full-Stack Development with MERN",
		skills: "MongoDB, Express, React, Node.js",
		rating: 4.6,
		reviews: "4K",
		level: "Advanced",
		type: "Guided Project",
		duration: "25 hours",
		img: mernImg,
	},
	{
		id: 8,
		name: "Building Mobile Apps with Flutter",
		skills: "Flutter, Dart, Mobile Development",
		rating: 4.8,
		reviews: "6K",
		level: "Intermediate",
		type: "Guided Project",
		duration: "15 hours",
		img: flutterImg,
	},
	{
		id: 9,
		name: "Introduction to Blockchain Development",
		skills: "Solidity, Ethereum, Smart Contracts",
		rating: 4.5,
		reviews: "2K",
		level: "Beginner",
		type: "Guided Project",
		duration: "10 hours",
		img: blockchainImg,
	},
	{
		id: 10,
		name: "Graphic Design Fundamentals",
		skills: "Adobe Illustrator, Photoshop, Design Principles",
		rating: 4.7,
		reviews: "5K",
		level: "Beginner",
		type: "Guided Project",
		duration: "10 hours",
		img: designImg,
	},
	{
		id: 11,
		name: "Data Visualization with Tableau",
		skills: "Tableau, Data Analysis, Dashboards",
		rating: 4.6,
		reviews: "3K",
		level: "Intermediate",
		type: "Guided Project",
		duration: "8 hours",
		img: tableauImg,
	},
	{
		id: 12,
		name: "Cybersecurity Basics",
		skills: "Network Security, Ethical Hacking, Risk Management",
		rating: 4.5,
		reviews: "4K",
		level: "Beginner",
		type: "Guided Project",
		duration: "12 hours",
		img: cybersecurityImg,
	},
	{
		id: 13,
		name: "Game Development with Unity",
		skills: "Unity, C#, Game Design",
		rating: 4.8,
		reviews: "3K",
		level: "Intermediate",
		type: "Guided Project",
		duration: "15 hours",
		img: unityImg,
	},
	{
		id: 14,
		name: "Introduction to Cloud Computing",
		skills: "AWS, Azure, Cloud Services",
		rating: 4.6,
		reviews: "7K",
		level: "Beginner",
		type: "Guided Project",
		duration: "10 hours",
		img: cloudImg,
	},
];

export const courseDetails = {
	"advanced-javascript-concepts": {
		content: [
			{
				id: 1,
				name: "Introduction to Programme",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 2,
				name: "Variables and Data Types",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Control Flow",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Functions",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "20 mins",
			},
		],
	},
	"responsive-web-design-with-css": {
		content: [
			{
				id: 1,
				name: "Introduction to Web Design",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "20 mins",
			},
			{
				id: 2,
				name: "CSS Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Flexbox Layouts",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Grid System",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "1 hour",
			},
		],
	},
	"building-restful-apis-with-nodejs": {
		content: [
			{
				id: 1,
				name: "Introduction to RESTful APIs",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "25 mins",
			},
			{
				id: 2,
				name: "Setting Up Node.js",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 3,
				name: "Express Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Working with MongoDB",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "1 hour 15 mins",
			},
		],
	},
	"introduction-to-vuejs": {
		content: [
			{
				id: 1,
				name: "Getting Started with Vue",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 2,
				name: "Data Binding",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Vue Components",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Event Handling",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "35 mins",
			},
		],
	},
	"python-for-data-science": {
		content: [
			{
				id: 1,
				name: "Python Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "40 mins",
			},
			{
				id: 2,
				name: "Data Analysis with Pandas",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 3,
				name: "Data Visualization",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "50 mins",
			},
			{
				id: 4,
				name: "Working with NumPy",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "45 mins",
			},
		],
	},
	"introduction-to-ml": {
		content: [
			{
				id: 1,
				name: "Introduction to Machine Learning",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 2,
				name: "Data Preprocessing",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "1 hour 15 mins",
			},
			{
				id: 3,
				name: "Training Models",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Evaluation Metrics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "45 mins",
			},
		],
	},
	"full-stack-development-with-mern": {
		content: [
			{
				id: 1,
				name: "Overview of MERN Stack",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 2,
				name: "Setting Up MongoDB",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 3,
				name: "Building RESTful APIs with Express",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour 15 mins",
			},
			{
				id: 4,
				name: "React for Frontend",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "1 hour",
			},
		],
	},
	"building-mobile-apps-with-flutter": {
		content: [
			{
				id: 1,
				name: "Introduction to Flutter",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 2,
				name: "Dart Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Creating Flutter Widgets",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Flutter State Management",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "50 mins",
			},
		],
	},
	"introduction-to-blockchain-development": {
		content: [
			{
				id: 1,
				name: "What is Blockchain?",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "25 mins",
			},
			{
				id: 2,
				name: "Introduction to Solidity",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Writing Smart Contracts",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Ethereum Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "50 mins",
			},
		],
	},
	"graphic-design-fundamentals": {
		content: [
			{
				id: 1,
				name: "Introduction to Graphic Design",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "20 mins",
			},
			{
				id: 2,
				name: "Working with Photoshop",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 3,
				name: "Illustrator Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Design Principles",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "45 mins",
			},
		],
	},
	"data-visualization-with-tableau": {
		content: [
			{
				id: 1,
				name: "Getting Started with Tableau",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 2,
				name: "Creating Dashboards",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Data Analysis Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Advanced Visualization Techniques",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "1 hour",
			},
		],
	},
	"cybersecurity-basics": {
		content: [
			{
				id: 1,
				name: "Cybersecurity Fundamentals",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "25 mins",
			},
			{
				id: 2,
				name: "Network Security Essentials",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "50 mins",
			},
			{
				id: 3,
				name: "Ethical Hacking Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Risk Management",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "45 mins",
			},
		],
	},
	"game-development-with-unity": {
		content: [
			{
				id: 1,
				name: "Getting Started with Unity",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "40 mins",
			},
			{
				id: 2,
				name: "Unity Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Introduction to C#",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "50 mins",
			},
			{
				id: 4,
				name: "Creating Game Mechanics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "1 hour",
			},
		],
	},
	"introduction-to-cloud-computing": {
		content: [
			{
				id: 1,
				name: "Overview of Cloud Computing",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "30 mins",
			},
			{
				id: 2,
				name: "Understanding AWS",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample2,
				type: "video",
				duration: "45 mins",
			},
			{
				id: 3,
				name: "Azure Basics",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample3,
				type: "video",
				duration: "1 hour",
			},
			{
				id: 4,
				name: "Other Cloud Services",
				icon: <FaRegPlayCircle className="text-2xl" />,
				vid: sample1,
				type: "video",
				duration: "50 mins",
			},
		],
	},
};

export const test = [
	{
		id: 1,
		name: "AI For Everyone",
		provider: "Coursera",
		description: "A non-technical introduction to artificial intelligence.",
		skills: ["AI", "Machine Learning", "Data Science"],
		rating: 4.7,
		reviews: "60K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "Free",
		courseOverview: {
			instructor: "Andrew Ng",
			instructor_bio:
				"Co-founder of Coursera and Professor at Stanford University.",
			enrollment: "400K+ students",
			language: "English",
			subtitles: ["English", "Spanish", "French"],
		},
		modules: [
			{
				module_id: "1",
				title: "What is AI?",
				module_description: "Understanding the basics of AI.",
				module_duration: "1 week",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Introduction to AI",
						content_type: "video",
						duration: "15 minutes",
						path: "/videos/introduction_to_ai.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "AI For Everyone Final Exam",
			questions: "10",
			duration: "30 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [
			{
				image_id: "cover",
				description: "Course cover image",
				path: "/images/course_cover.jpg",
			},
		],
	},
	{
		id: 2,
		name: "Deep Learning Specialization",
		provider: "Coursera",
		description: "Learn about deep learning and how to build neural networks.",
		skills: ["Deep Learning", "Neural Networks"],
		rating: 4.9,
		reviews: "50K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "3 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Andrew Ng",
			instructor_bio: "Leading AI researcher and educator.",
			enrollment: "300K+ students",
			language: "English",
			subtitles: ["English", "Chinese"],
		},
		modules: [
			{
				module_id: "1",
				title: "Neural Networks and Deep Learning",
				module_description: "Introduction to neural networks.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Introduction to Neural Networks",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/intro_to_neural_networks.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Deep Learning Specialization Final Exam",
			questions: "25",
			duration: "90 minutes",
			passing_score: "80%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 3,
		name: "Data Science Specialization",
		provider: "Coursera",
		description: "A comprehensive introduction to data science.",
		skills: ["Data Science", "R Programming"],
		rating: 4.8,
		reviews: "45K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "10 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Jeff Leek, Roger D. Peng, Brian Caffo",
			instructor_bio:
				"Professors in the Department of Statistics at Johns Hopkins University.",
			enrollment: "100K+ students",
			language: "English",
			subtitles: ["English", "Spanish", "Chinese"],
		},
		modules: [
			{
				module_id: "1",
				title: "The Data Scientist’s Toolbox",
				module_description: "Introduction to the tools used in data science.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Tools for Data Science",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/tools_for_data_science.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Data Science Specialization Final Exam",
			questions: "30",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 4,
		name: "Machine Learning",
		provider: "Coursera",
		description:
			"A comprehensive introduction to machine learning, data mining, and statistical pattern recognition.",
		skills: ["Machine Learning", "Data Mining", "Statistics"],
		rating: 4.9,
		reviews: "75K+",
		level: "Beginner",
		type: "Course",
		duration: "11 weeks",
		price: "Free",
		courseOverview: {
			instructor: "Andrew Ng",
			instructor_bio: "Co-founder of Coursera and Stanford professor.",
			enrollment: "500K+ students",
			language: "English",
			subtitles: ["English", "Spanish", "French"],
		},
		modules: [
			{
				module_id: "1",
				title: "Supervised Learning",
				module_description: "Introduction to supervised learning techniques.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Linear Regression",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/linear_regression.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Machine Learning Final Exam",
			questions: "40",
			duration: "120 minutes",
			passing_score: "80%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 5,
		name: "Introduction to TensorFlow for Artificial Intelligence, Machine Learning, and Deep Learning",
		provider: "Coursera",
		description: "Learn how to use TensorFlow for AI and machine learning.",
		skills: ["TensorFlow", "Machine Learning", "Deep Learning"],
		rating: 4.6,
		reviews: "30K+",
		level: "Intermediate",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Laurence Moroney",
			instructor_bio: "AI Advocate at Google and TensorFlow expert.",
			enrollment: "200K+ students",
			language: "English",
			subtitles: ["English", "Spanish"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to TensorFlow",
				module_description: "Basics of TensorFlow and its applications.",
				module_duration: "2 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Getting Started with TensorFlow",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/getting_started_with_tensorflow.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "TensorFlow AI Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 6,
		name: "Python for Everybody",
		provider: "Coursera",
		description: "Learn to program and analyze data using Python.",
		skills: ["Python", "Data Analysis", "Programming"],
		rating: 4.8,
		reviews: "65K+",
		level: "Beginner",
		type: "Specialization",
		duration: "5 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Charles Severance",
			instructor_bio: "Clinical Professor at the University of Michigan.",
			enrollment: "400K+ students",
			language: "English",
			subtitles: ["English", "Chinese"],
		},
		modules: [
			{
				module_id: "1",
				title: "Programming for Everybody",
				module_description: "An introduction to programming using Python.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Python Basics",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/python_basics.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Python for Everybody Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 7,
		name: "Data Analysis with Python",
		provider: "Coursera",
		description: "Learn data analysis using Python.",
		skills: ["Data Analysis", "Python", "Data Science"],
		rating: 4.5,
		reviews: "20K+",
		level: "Intermediate",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Jamal Moustafa",
			instructor_bio: "Data Scientist and AI Engineer.",
			enrollment: "80K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to Data Analysis",
				module_description: "Basics of data analysis and visualization.",
				module_duration: "2 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Data Visualization Techniques",
						content_type: "video",
						duration: "15 minutes",
						path: "/videos/data_visualization_techniques.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Data Analysis Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 8,
		name: "Statistics for Data Science",
		provider: "Coursera",
		description: "Learn statistics for data science and analytics.",
		skills: ["Statistics", "Data Analysis"],
		rating: 4.4,
		reviews: "25K+",
		level: "Beginner",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Mine Çetinkaya-Rundel",
			instructor_bio: "Statistician and educator.",
			enrollment: "50K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to Statistics",
				module_description: "Basics of statistics for data analysis.",
				module_duration: "3 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Descriptive Statistics",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/descriptive_statistics.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Statistics for Data Science Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 9,
		name: "SQL for Data Science",
		provider: "Coursera",
		description: "Learn SQL for data science and analytics.",
		skills: ["SQL", "Data Analysis"],
		rating: 4.6,
		reviews: "15K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Daniel Chen",
			instructor_bio: "Data Scientist and SQL expert.",
			enrollment: "70K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to SQL",
				module_description: "Basics of SQL for data analysis.",
				module_duration: "2 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Basic SQL Queries",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/basic_sql_queries.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "SQL for Data Science Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 10,
		name: "Cloud Computing Specialization",
		provider: "Coursera",
		description: "Learn cloud computing from the ground up.",
		skills: ["Cloud Computing", "AWS", "Google Cloud"],
		rating: 4.8,
		reviews: "22K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "3 months",
		price: "$49/month",
		courseOverview: {
			instructor: "M. A. Khan",
			instructor_bio: "Cloud solutions architect and educator.",
			enrollment: "40K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Cloud Computing Basics",
				module_description: "Introduction to cloud computing concepts.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "What is Cloud Computing?",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/what_is_cloud_computing.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Cloud Computing Specialization Final Exam",
			questions: "30",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 11,
		name: "Full Stack Web Development Specialization",
		provider: "Coursera",
		description:
			"Learn full stack web development using HTML, CSS, and JavaScript.",
		skills: ["Web Development", "HTML", "CSS", "JavaScript"],
		rating: 4.7,
		reviews: "55K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "4 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Yogesh Patel",
			instructor_bio:
				"Web developer with experience in full stack technologies.",
			enrollment: "60K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "HTML and CSS Basics",
				module_description: "Learn the basics of HTML and CSS.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Introduction to HTML",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/intro_to_html.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Full Stack Development Final Exam",
			questions: "30",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 12,
		name: "Digital Marketing Specialization",
		provider: "Coursera",
		description: "Learn digital marketing strategies and techniques.",
		skills: ["Digital Marketing", "SEO", "Content Marketing"],
		rating: 4.5,
		reviews: "40K+",
		level: "Beginner",
		type: "Specialization",
		duration: "6 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Diana H. Wong",
			instructor_bio: "Digital marketing expert and consultant.",
			enrollment: "75K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Fundamentals of Digital Marketing",
				module_description: "Introduction to digital marketing concepts.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Digital Marketing Overview",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/digital_marketing_overview.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Digital Marketing Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 13,
		name: "Cybersecurity Specialization",
		provider: "Coursera",
		description: "Learn about cybersecurity from a foundational level.",
		skills: ["Cybersecurity", "Network Security"],
		rating: 4.6,
		reviews: "30K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "3 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Charles H. Davis",
			instructor_bio: "Cybersecurity researcher and educator.",
			enrollment: "40K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to Cybersecurity",
				module_description: "Basics of cybersecurity concepts.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Cybersecurity Principles",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/cybersecurity_principles.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Cybersecurity Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 14,
		name: "Graphic Design Specialization",
		provider: "Coursera",
		description: "Learn the fundamentals of graphic design.",
		skills: ["Graphic Design", "Adobe Photoshop", "Creativity"],
		rating: 4.8,
		reviews: "18K+",
		level: "Beginner",
		type: "Specialization",
		duration: "4 months",
		price: "$49/month",
		courseOverview: {
			instructor: "David T. Jones",
			instructor_bio: "Graphic designer and educator.",
			enrollment: "30K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to Graphic Design",
				module_description: "Basics of graphic design principles.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Design Basics",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/design_basics.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Graphic Design Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 15,
		name: "Blockchain Basics",
		provider: "Coursera",
		description: "An introduction to blockchain technology.",
		skills: ["Blockchain", "Cryptocurrency"],
		rating: 4.5,
		reviews: "10K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "Free",
		courseOverview: {
			instructor: "Pavol Kapanek",
			instructor_bio: "Blockchain technology expert.",
			enrollment: "15K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Blockchain Overview",
				module_description: "Basics of blockchain technology.",
				module_duration: "2 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "What is Blockchain?",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/what_is_blockchain.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Blockchain Basics Final Exam",
			questions: "10",
			duration: "30 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 16,
		name: "Introduction to HTML, CSS, and JavaScript",
		provider: "Coursera",
		description:
			"Learn the basics of web development with HTML, CSS, and JavaScript.",
		skills: ["HTML", "CSS", "JavaScript"],
		rating: 4.4,
		reviews: "12K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "John Doe",
			instructor_bio: "Web developer and educator.",
			enrollment: "20K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Getting Started with HTML",
				module_description: "Basics of HTML for web development.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "HTML Syntax",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/html_syntax.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "HTML, CSS, JavaScript Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 17,
		name: "Foundations of Project Management",
		provider: "Coursera",
		description: "Learn the basics of project management.",
		skills: ["Project Management", "Leadership"],
		rating: 4.6,
		reviews: "20K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "James E. Smith",
			instructor_bio: "Project manager and educator.",
			enrollment: "25K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Project Management Basics",
				module_description: "An introduction to project management principles.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Understanding Project Management",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/understanding_project_management.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Project Management Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 18,
		name: "Introduction to Artificial Intelligence",
		provider: "Coursera",
		description: "Explore the fundamentals of AI.",
		skills: ["AI", "Data Science"],
		rating: 4.7,
		reviews: "25K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Aisha Khan",
			instructor_bio: "AI researcher and educator.",
			enrollment: "60K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to AI",
				module_description: "Basics of artificial intelligence.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "What is AI?",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/what_is_ai.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "AI Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 19,
		name: "Introduction to Mobile App Development",
		provider: "Coursera",
		description: "Learn the basics of mobile app development.",
		skills: ["Mobile Development", "Java", "Kotlin"],
		rating: 4.6,
		reviews: "15K+",
		level: "Beginner",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Samuel Lee",
			instructor_bio: "Mobile app developer and educator.",
			enrollment: "30K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Getting Started with Mobile Development",
				module_description: "Basics of mobile app development.",
				module_duration: "3 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Android Basics",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/android_basics.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Mobile App Development Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 20,
		name: "Introduction to Game Development",
		provider: "Coursera",
		description: "Learn the fundamentals of game development.",
		skills: ["Game Development", "Unity", "C#"],
		rating: 4.3,
		reviews: "12K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Emily White",
			instructor_bio: "Game developer and educator.",
			enrollment: "10K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Game Development Basics",
				module_description: "Introduction to game development concepts.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Introduction to Unity",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/introduction_to_unity.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Game Development Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 21,
		name: "Introduction to Data Science",
		provider: "Coursera",
		description:
			"An introductory course on data science concepts and methodologies.",
		skills: ["Data Science", "Statistics", "Machine Learning"],
		rating: 4.6,
		reviews: "22K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Tom Johnson",
			instructor_bio:
				"Data scientist and educator with a focus on machine learning.",
			enrollment: "50K+ students",
			language: "English",
			subtitles: ["English", "Spanish"],
		},
		modules: [
			{
				module_id: "1",
				title: "Data Science Basics",
				module_description: "Fundamentals of data science.",
				module_duration: "5 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "What is Data Science?",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/what_is_data_science.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Data Science Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 22,
		name: "Machine Learning A-Z",
		provider: "Coursera",
		description:
			"A comprehensive guide to machine learning concepts and techniques.",
		skills: ["Machine Learning", "Data Analysis", "Python"],
		rating: 4.7,
		reviews: "28K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "3 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Andrew Ng",
			instructor_bio: "Machine learning pioneer and educator.",
			enrollment: "100K+ students",
			language: "English",
			subtitles: ["English", "Chinese"],
		},
		modules: [
			{
				module_id: "1",
				title: "Supervised Learning",
				module_description: "Introduction to supervised learning techniques.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Linear Regression",
						content_type: "video",
						duration: "40 minutes",
						path: "/videos/linear_regression.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Machine Learning Final Exam",
			questions: "30",
			duration: "90 minutes",
			passing_score: "80%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 23,
		name: "Digital Photography Basics",
		provider: "Coursera",
		description: "Learn the fundamentals of digital photography.",
		skills: ["Photography", "Image Editing"],
		rating: 4.5,
		reviews: "18K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Mark Stevens",
			instructor_bio: "Professional photographer and educator.",
			enrollment: "15K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Camera Basics",
				module_description: "Understanding how cameras work.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Understanding Aperture",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/understanding_aperture.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Photography Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 24,
		name: "Data Analysis with R",
		provider: "Coursera",
		description: "Learn data analysis techniques using R programming.",
		skills: ["R", "Data Analysis", "Statistics"],
		rating: 4.6,
		reviews: "12K+",
		level: "Intermediate",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Jane Doe",
			instructor_bio: "Data analyst and educator.",
			enrollment: "30K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to R",
				module_description: "Basics of R programming for data analysis.",
				module_duration: "6 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "R Basics",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/r_basics.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "R Data Analysis Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 25,
		name: "Financial Markets",
		provider: "Coursera",
		description:
			"Explore the dynamics of financial markets and their role in the economy.",
		skills: ["Finance", "Economics"],
		rating: 4.4,
		reviews: "15K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "Free",
		courseOverview: {
			instructor: "Dr. Robert Shiller",
			instructor_bio: "Nobel laureate in Economics and educator.",
			enrollment: "40K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Overview of Financial Markets",
				module_description:
					"Introduction to different types of financial markets.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Stock Markets",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/stock_markets.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Financial Markets Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 26,
		name: "Introduction to SQL",
		provider: "Coursera",
		description: "Learn the basics of SQL for database management.",
		skills: ["SQL", "Database Management"],
		rating: 4.5,
		reviews: "10K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Samantha Lee",
			instructor_bio: "Database administrator and educator.",
			enrollment: "25K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "SQL Fundamentals",
				module_description: "Basics of SQL for data retrieval.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "SQL Syntax",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/sql_syntax.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "SQL Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 27,
		name: "Cybersecurity Fundamentals",
		provider: "Coursera",
		description: "Introduction to cybersecurity principles and practices.",
		skills: ["Cybersecurity", "Network Security"],
		rating: 4.8,
		reviews: "30K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. James Smith",
			instructor_bio: "Cybersecurity expert and educator.",
			enrollment: "55K+ students",
			language: "English",
			subtitles: ["English", "Spanish"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to Cybersecurity",
				module_description: "Basics of cybersecurity and threat management.",
				module_duration: "5 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Understanding Cyber Threats",
						content_type: "video",
						duration: "35 minutes",
						path: "/videos/understanding_cyber_threats.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Cybersecurity Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 28,
		name: "Introduction to Cloud Computing",
		provider: "Coursera",
		description: "Learn the fundamentals of cloud computing.",
		skills: ["Cloud Computing", "AWS", "Azure"],
		rating: 4.5,
		reviews: "20K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Anna Bright",
			instructor_bio: "Cloud architect and educator.",
			enrollment: "45K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Cloud Computing Basics",
				module_description: "Introduction to cloud services and deployment.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Types of Cloud Services",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/types_of_cloud_services.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Cloud Computing Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 29,
		name: "Foundations of Project Management",
		provider: "Coursera",
		description: "Explore the core principles of project management.",
		skills: ["Project Management", "Agile", "Scrum"],
		rating: 4.6,
		reviews: "18K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Sarah Johnson",
			instructor_bio: "Project manager and educator.",
			enrollment: "30K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Introduction to Project Management",
				module_description: "Fundamentals of managing projects.",
				module_duration: "5 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Project Lifecycle",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/project_lifecycle.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Project Management Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 30,
		name: "Social Media Marketing",
		provider: "Coursera",
		description: "Learn the strategies of effective social media marketing.",
		skills: ["Marketing", "Social Media", "Branding"],
		rating: 4.3,
		reviews: "20K+",
		level: "Beginner",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Laura Chen",
			instructor_bio: "Digital marketing expert.",
			enrollment: "50K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Social Media Platforms",
				module_description: "Understanding different social media platforms.",
				module_duration: "6 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Facebook Marketing",
						content_type: "video",
						duration: "20 minutes",
						path: "/videos/facebook_marketing.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Social Media Marketing Final Exam",
			questions: "15",
			duration: "45 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 31,
		name: "Artificial Intelligence for Beginners",
		provider: "Coursera",
		description: "A comprehensive introduction to the basics of AI.",
		skills: ["AI", "Machine Learning"],
		rating: 4.5,
		reviews: "20K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Chris Williams",
			instructor_bio: "AI specialist with years of teaching experience.",
			enrollment: "40K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "AI Concepts",
				module_description: "Understanding key AI concepts.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "What is Artificial Intelligence?",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/what_is_ai.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "AI for Beginners Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 32,
		name: "Statistics for Data Science",
		provider: "Coursera",
		description: "Explore essential statistical concepts used in data science.",
		skills: ["Statistics", "Data Science"],
		rating: 4.6,
		reviews: "15K+",
		level: "Intermediate",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Linda Smith",
			instructor_bio: "Statistician and educator.",
			enrollment: "35K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Statistical Concepts",
				module_description: "Introduction to key statistical concepts.",
				module_duration: "6 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Descriptive Statistics",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/descriptive_statistics.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Statistics Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 33,
		name: "Game Development for Beginners",
		provider: "Coursera",
		description: "Learn the basics of game development.",
		skills: ["Game Development", "Programming"],
		rating: 4.4,
		reviews: "10K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Jason Brown",
			instructor_bio: "Game developer and educator.",
			enrollment: "25K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Game Development Basics",
				module_description: "Introduction to game design and development.",
				module_duration: "5 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Understanding Game Engines",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/understanding_game_engines.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Game Development Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 34,
		name: "Introduction to Web Development",
		provider: "Coursera",
		description: "Learn the basics of web development and design.",
		skills: ["HTML", "CSS", "JavaScript"],
		rating: 4.5,
		reviews: "30K+",
		level: "Beginner",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Emily Clarke",
			instructor_bio: "Web developer and educator.",
			enrollment: "50K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Web Development Basics",
				module_description: "Introduction to HTML, CSS, and JavaScript.",
				module_duration: "6 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Getting Started with HTML",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/getting_started_html.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Web Development Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 35,
		name: "Creative Writing Specialization",
		provider: "Coursera",
		description:
			"Enhance your creative writing skills with this specialization.",
		skills: ["Creative Writing", "Storytelling"],
		rating: 4.8,
		reviews: "12K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "3 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Robert Frost",
			instructor_bio: "Acclaimed author and writing instructor.",
			enrollment: "20K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Writing Fiction",
				module_description: "Techniques for writing engaging fiction.",
				module_duration: "8 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Character Development",
						content_type: "video",
						duration: "35 minutes",
						path: "/videos/character_development.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Creative Writing Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 36,
		name: "Digital Marketing Specialization",
		provider: "Coursera",
		description: "Master digital marketing strategies and tools.",
		skills: ["Digital Marketing", "SEO", "Content Marketing"],
		rating: 4.7,
		reviews: "25K+",
		level: "Intermediate",
		type: "Specialization",
		duration: "6 months",
		price: "$49/month",
		courseOverview: {
			instructor: "Sarah Gold",
			instructor_bio: "Digital marketing strategist and educator.",
			enrollment: "35K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "SEO Fundamentals",
				module_description: "Understanding SEO and its importance.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Keyword Research",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/keyword_research.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Digital Marketing Final Exam",
			questions: "30",
			duration: "90 minutes",
			passing_score: "75%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 37,
		name: "Public Speaking for Professionals",
		provider: "Coursera",
		description: "Develop effective public speaking skills.",
		skills: ["Public Speaking", "Communication"],
		rating: 4.5,
		reviews: "15K+",
		level: "Beginner",
		type: "Course",
		duration: "4 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "David Johnson",
			instructor_bio: "Public speaking coach and educator.",
			enrollment: "20K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Public Speaking Basics",
				module_description: "Fundamentals of effective public speaking.",
				module_duration: "4 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Overcoming Stage Fright",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/overcoming_stage_fright.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Public Speaking Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 38,
		name: "Introduction to Blockchain",
		provider: "Coursera",
		description: "Explore the technology behind blockchain.",
		skills: ["Blockchain", "Cryptocurrency"],
		rating: 4.6,
		reviews: "10K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Mike Lee",
			instructor_bio: "Blockchain expert and educator.",
			enrollment: "15K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Blockchain Basics",
				module_description: "Introduction to blockchain technology.",
				module_duration: "5 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Understanding Decentralization",
						content_type: "video",
						duration: "35 minutes",
						path: "/videos/understanding_decentralization.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Blockchain Final Exam",
			questions: "25",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 39,
		name: "Data Analysis with Python",
		provider: "Coursera",
		description: "Learn data analysis techniques using Python.",
		skills: ["Python", "Data Analysis"],
		rating: 4.7,
		reviews: "22K+",
		level: "Intermediate",
		type: "Course",
		duration: "6 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Dr. Alice Wang",
			instructor_bio: "Data scientist and educator.",
			enrollment: "25K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Data Analysis Basics",
				module_description: "Introduction to data analysis using Python.",
				module_duration: "6 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Data Cleaning Techniques",
						content_type: "video",
						duration: "30 minutes",
						path: "/videos/data_cleaning_techniques.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Data Analysis Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
	{
		id: 40,
		name: "Digital Art and Design",
		provider: "Coursera",
		description: "Explore digital art and design techniques.",
		skills: ["Digital Art", "Design"],
		rating: 4.6,
		reviews: "8K+",
		level: "Beginner",
		type: "Course",
		duration: "5 weeks",
		price: "$49/month",
		courseOverview: {
			instructor: "Megan Hill",
			instructor_bio: "Digital artist and educator.",
			enrollment: "10K+ students",
			language: "English",
			subtitles: ["English"],
		},
		modules: [
			{
				module_id: "1",
				title: "Digital Art Basics",
				module_description: "Introduction to digital art techniques.",
				module_duration: "5 weeks",
				lessons: [
					{
						lesson_id: "1.1",
						title: "Using Digital Tools",
						content_type: "video",
						duration: "25 minutes",
						path: "/videos/using_digital_tools.mp4",
					},
				],
			},
		],
		resources: [],
		exam: {
			exam_id: "final_exam",
			title: "Digital Art Final Exam",
			questions: "20",
			duration: "60 minutes",
			passing_score: "70%",
			path: "/exams/final_exam.html",
		},
		images: [],
	},
];

export const courses = [
	{
		id: "60f5b704fc13ae34d201c6f3",
		course_title:
			"English for Common Interactions in the Workplace: Basic Level",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/english-common-interactions-workplace-basic-level",
		description:
			"This course equips learners with essential English communication skills for common workplace interactions.",
		language: "English",
		duration: {
			total_hours: 8,
			weeks: 3,
			weekly_effort_hours: 2,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Basic English communication",
			"Workplace etiquette",
			"Making and receiving phone calls",
		],
		instructors: [
			{
				name: "James Gibbons",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/jamesgibbons",
			},
			{
				name: "Paula Ross",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/paulaross",
			},
		],
		ratings: {
			average_rating: 4.5,
			number_of_reviews: 150,
			enrollment: 1200,
			liked_percent: 90,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6f4",
		course_title: "Machine Learning",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/machine-learning",
		description:
			"Learn the fundamentals of machine learning, data mining, and statistical pattern recognition.",
		language: "English",
		duration: {
			total_hours: 55,
			weeks: 11,
			weekly_effort_hours: 5,
		},
		difficulty_level: "Intermediate",
		skills_covered: [
			"Supervised learning",
			"Unsupervised learning",
			"Reinforcement learning",
			"Data analysis",
		],
		instructors: [
			{
				name: "Andrew Ng",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/andrewyng",
			},
		],
		ratings: {
			average_rating: 4.8,
			number_of_reviews: 1500,
			enrollment: 800,
			liked_percent: 96,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$79",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6f5",
		course_title: "Data Science Specialization",
		platform: "Coursera",
		url: "https://www.coursera.org/specializations/jhu-data-science",
		description:
			"A comprehensive introduction to data science, covering R programming, data analysis, and machine learning.",
		language: "English",
		duration: {
			total_hours: 70,
			weeks: 12,
			weekly_effort_hours: 5,
		},
		difficulty_level: "Intermediate",
		skills_covered: [
			"R programming",
			"Statistical inference",
			"Machine learning",
			"Data visualization",
		],
		instructors: [
			{
				name: "Jeff Leek",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/jtleek",
			},
			{
				name: "Roger D. Peng",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/rogerpeng",
			},
		],
		ratings: {
			average_rating: 4.5,
			number_of_reviews: 87987,
			enrollment: 9867,
			liked_percent: 87,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$399",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6f6",
		course_title: "The Science of Well-Being",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/the-science-of-well-being",
		description:
			"Learn about the science of happiness and how to apply it to improve your own well-being.",
		language: "English",
		duration: {
			total_hours: 19,
			weeks: 10,
			weekly_effort_hours: 2,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Positive psychology",
			"Mindfulness",
			"Happiness strategies",
		],
		instructors: [
			{
				name: "Laurie Santos",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/lauriesantos",
			},
		],
		ratings: {
			average_rating: 4.1,
			number_of_reviews: 1250,
			enrollment: 9200,
			liked_percent: 93,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6f7",
		course_title:
			"Introduction to Computer Science and Programming Using Python",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/python",
		description:
			"An introduction to computer science as a tool to solve real-world analytical problems.",
		language: "English",
		duration: {
			total_hours: 50,
			weeks: 9,
			weekly_effort_hours: 5,
		},
		difficulty_level: "Beginner",
		skills_covered: ["Python programming", "Data analysis", "Algorithm design"],
		instructors: [
			{
				name: "Eric Grimson",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/egrimson",
			},
			{
				name: "John Guttag",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/jguttag",
			},
		],
		ratings: {
			average_rating: 4.0,
			number_of_reviews: 650,
			enrollment: 5200,
			liked_percent: 85,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$75",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6f8",
		course_title: "Digital Marketing Specialization",
		platform: "Coursera",
		url: "https://www.coursera.org/specializations/digital-marketing",
		description:
			"Learn digital marketing concepts and skills, including analytics, social media, and content marketing.",
		language: "English",
		duration: {
			total_hours: 20,
			weeks: 5,
			weekly_effort_hours: 4,
		},
		difficulty_level: "Intermediate",
		skills_covered: [
			"SEO",
			"Social media marketing",
			"Email marketing",
			"Content strategy",
		],
		instructors: [
			{
				name: "Dhruv Grewal",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/dhruvgrewal",
			},
		],
		ratings: {
			average_rating: 4.4,
			number_of_reviews: 987,
			enrollment: 9878,
			liked_percent: 94,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$199",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6f9",
		course_title: "Introduction to Psychology",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/psychology",
		description:
			"Explore the science of psychology and understand how it impacts human behavior.",
		language: "English",
		duration: {
			total_hours: 12,
			weeks: 4,
			weekly_effort_hours: 3,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Cognitive psychology",
			"Behavioral psychology",
			"Social psychology",
		],
		instructors: [
			{
				name: "Paul Bloom",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/paulbloom",
			},
		],
		ratings: {
			average_rating: 4.7,
			number_of_reviews: 5580,
			enrollment: 9807,
			liked_percent: 89,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6fa",
		course_title: "Artificial Intelligence for Everyone",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/ai-for-everyone",
		description:
			"An introduction to artificial intelligence and its impact on society and business.",
		language: "English",
		duration: {
			total_hours: 6,
			weeks: 4,
			weekly_effort_hours: 1.5,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"AI concepts",
			"Business applications of AI",
			"Ethics in AI",
		],
		instructors: [
			{
				name: "Andrew Ng",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/andrewyng",
			},
		],
		ratings: {
			average_rating: 4.8,
			number_of_reviews: 1500,
			enrollment: 800,
			liked_percent: 96,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6fb",
		course_title: "Financial Markets",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/financial-markets",
		description:
			"Learn about the role of financial markets in the economy and how to invest wisely.",
		language: "English",
		duration: {
			total_hours: 37,
			weeks: 7,

			weekly_effort_hours: 5,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Investment strategies",
			"Risk management",
			"Market analysis",
		],
		instructors: [
			{
				name: "Robert Shiller",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/shiller",
			},
		],
		ratings: {
			average_rating: 4.4,
			number_of_reviews: 987,
			enrollment: 9878,
			liked_percent: 94,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6fc",
		course_title: "Programming for Everybody (Getting Started with JavaScript)",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/javascript",
		description:
			"An introduction to programming using JavaScript, focusing on the basics of programming and problem-solving.",
		language: "English",
		duration: {
			total_hours: 20,
			weeks: 4,
			weekly_effort_hours: 5,
		},
		difficulty_level: "Beginner",
		skills_covered: ["JavaScript basics", "Problem-solving", "Web development"],
		instructors: [
			{
				name: "Charles Severance",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/drchuck",
			},
		],
		ratings: {
			average_rating: 4.9,
			number_of_reviews: 67876,
			enrollment: 97546,
			liked_percent: 98,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6fd",
		course_title: "Graphic Design Specialization",
		platform: "Coursera",
		url: "https://www.coursera.org/specializations/graphic-design",
		description:
			"Learn the fundamentals of graphic design, including typography, color theory, and visual hierarchy.",
		language: "English",
		duration: {
			total_hours: 45,
			weeks: 5,
			weekly_effort_hours: 6,
		},
		difficulty_level: "Intermediate",
		skills_covered: [
			"Graphic design principles",
			"Visual communication",
			"Adobe Photoshop",
		],
		instructors: [
			{
				name: "David Kelley",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/davidkelley",
			},
		],
		ratings: {
			average_rating: 4.7,
			number_of_reviews: 5580,
			enrollment: 9807,
			liked_percent: 89,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$199",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6fe",
		course_title: "Digital Product Management",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/digital-product-management",
		description:
			"Learn the key principles of digital product management and how to build successful products.",
		language: "English",
		duration: {
			total_hours: 16,
			weeks: 4,
			weekly_effort_hours: 4,
		},
		difficulty_level: "Intermediate",
		skills_covered: [
			"Product lifecycle",
			"Agile development",
			"User-centered design",
		],
		instructors: [
			{
				name: "Christian Terwiesch",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/terwiesch",
			},
		],
		ratings: {
			average_rating: 4.4,
			number_of_reviews: 987,
			enrollment: 9878,
			liked_percent: 94,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$79",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c6ff",
		course_title: "Cybersecurity Specialization",
		platform: "Coursera",
		url: "https://www.coursera.org/specializations/cyber-security",
		description:
			"Gain foundational skills in cybersecurity, including risk assessment, cryptography, and security principles.",
		language: "English",
		duration: {
			total_hours: 40,
			weeks: 5,
			weekly_effort_hours: 8,
		},
		difficulty_level: "Intermediate",
		skills_covered: [
			"Network security",
			"Security protocols",
			"Risk management",
		],
		instructors: [
			{
				name: "R. Kevin McCarthy",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/rkevinmccarthy",
			},
		],
		ratings: {
			average_rating: 4.8,
			number_of_reviews: 1500,
			enrollment: 800,
			liked_percent: 96,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$199",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c700",
		course_title: "Python for Everybody",
		platform: "Coursera",
		url: "https://www.coursera.org/specializations/python",
		description:
			"Learn to program in Python and improve your data analysis skills.",
		language: "English",
		duration: {
			total_hours: 40,
			weeks: 5,
			weekly_effort_hours: 8,
		},
		difficulty_level: "Beginner",
		skills_covered: ["Python programming", "Data manipulation", "Web scraping"],
		instructors: [
			{
				name: "Charles Severance",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/drchuck",
			},
		],
		ratings: {
			average_rating: 4.7,
			number_of_reviews: 5580,
			enrollment: 9807,
			liked_percent: 89,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c701",
		course_title: "Introduction to Quantum Computing",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/quantum-computing",
		description:
			"Learn the fundamentals of quantum computing and its applications in modern technology.",
		language: "English",
		duration: {
			total_hours: 20,
			weeks: 4,
			weekly_effort_hours: 5,
		},
		difficulty_level: "Intermediate",
		skills_covered: ["Quantum mechanics", "Quantum algorithms", "Cryptography"],
		instructors: [
			{
				name: "John Preskill",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/jpreskill",
			},
		],
		ratings: {
			average_rating: 4.6,
			number_of_reviews: 15687,
			enrollment: 8659,
			liked_percent: 95,
		},
		certificate: {
			offered: true,
			type: "Shareable Certificate",
			price: "$49",
			financial_aid: true,
		},
	},
	{
		id: "60f5b704fc13ae34d201c702",
		course_title: "Introduction to Data Science",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/data-science",
		description:
			"Explore the field of data science, including data analysis and visualization techniques.",
		language: "English",
		duration: {
			total_hours: 40,
			weeks: 4,
			weekly_effort_hours: 10,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Data analysis",
			"Data visualization",
			"Statistical inference",
		],
		instructors: [
			{
				name: "Marta N. N. Mendes",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/martanm",
			},
		],
		ratings: {
			average_rating: 4.4,
			number_of_reviews: 987,
			enrollment: 9878,
			liked_percent: 94,
		},
		certificate: {
			offered: false,
		},
	},
	{
		id: "60f5b704fc13ae34d201c703",
		course_title: "COVID-19 Contact Tracing",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/covid-19-contact-tracing",
		description:
			"Learn about the principles of contact tracing and its role in controlling the COVID-19 pandemic.",
		language: "English",
		duration: {
			total_hours: 4,
			weeks: 1,
			weekly_effort_hours: 4,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Epidemiology",
			"Contact tracing",
			"Public health strategies",
		],
		instructors: [
			{
				name: "Yale University",
				title: "Institution",
				profile_url: "https://www.coursera.org/instructor/yale",
			},
		],
		ratings: {
			average_rating: 4.8,
			number_of_reviews: 1500,
			enrollment: 800,
			liked_percent: 96,
		},
		certificate: {
			offered: false,
		},
	},
	{
		id: "60f5b704fc13ae34d201c704",
		course_title: "AI For Everyone",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/ai-for-everyone",
		description:
			"An introduction to artificial intelligence, its applications, and how it affects our lives.",
		language: "English",
		duration: {
			total_hours: 8,
			weeks: 4,
			weekly_effort_hours: 2,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Understanding AI",
			"Machine learning concepts",
			"AI applications",
		],
		instructors: [
			{
				name: "Andrew Ng",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/andrewwng",
			},
		],
		ratings: {
			average_rating: 4.7,
			number_of_reviews: 5500,
			enrollment: 8089,
			liked_percent: 90,
		},
		certificate: {
			offered: false,
		},
	},
	{
		id: "60f5b704fc13ae34d201c705",
		course_title: "The Science of Well-Being",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/the-science-of-well-being",
		description:
			"Learn about the psychology of happiness and how to build a fulfilling life.",
		language: "English",
		duration: {
			total_hours: 19,
			weeks: 10,
			weekly_effort_hours: 2,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Positive psychology",
			"Behavioral science",
			"Habit formation",
		],
		instructors: [
			{
				name: "Laurie Santos",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/lauriesantos",
			},
		],
		ratings: {
			average_rating: 4.4,
			number_of_reviews: 987,
			enrollment: 9878,
			liked_percent: 94,
		},
		certificate: {
			offered: false,
		},
	},
	{
		id: "60f5b704fc13ae34d201c706",
		course_title: "Learning How to Learn",
		platform: "Coursera",
		url: "https://www.coursera.org/learn/learning-how-to-learn",
		description:
			"Learn effective learning techniques from neuroscience and cognitive psychology.",
		language: "English",
		duration: {
			total_hours: 15,
			weeks: 4,
			weekly_effort_hours: 3.5,
		},
		difficulty_level: "Beginner",
		skills_covered: [
			"Study techniques",
			"Memory enhancement",
			"Time management",
		],
		instructors: [
			{
				name: "Barbara Oakley",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/barbaraoakley",
			},
			{
				name: "Terrence Sejnowski",
				title: "Instructor",
				profile_url: "https://www.coursera.org/instructor/terrysejnowski",
			},
		],
		ratings: {
			average_rating: 4.7,
			number_of_reviews: 5580,
			enrollment: 9807,
			liked_percent: 89,
		},
		certificate: {
			offered: false,
		},
	},
];
